#
# Require a .env file contains all environment vars
# look contents of file _dot.env.example
#
version: '3'

networks:
  default:
    driver: bridge

services:

  peliaslite:
    container_name: peliaslite
    ports:
      - "8088:8088"
    image: peliaslite:latest
    build:
      context: ./
    environment:
      OTP_HOST: otp
      OTP_PATH: /otp/routers/default
      OTP_PORT: 8080
      HERE_APPID: ''
      HERE_APPCODE: ''
      HERE_APIKEY: ''
